### Viewing Processed Datasets

In [5]:
import pandas as pd

ff3 = pd.read_parquet("../data/processed/ff3_monthly.parquet")
mom = pd.read_parquet("../data/processed/mom_monthly.parquet")
factors = pd.read_parquet("../data/processed/factors_monthly.parquet")
rets = pd.read_parquet("../data/processed/returns_monthly.parquet")
ports = pd.read_parquet("../data/processed/portfolios_25_5x5_monthly.parquet")

display(ff3.head())
display(factors.describe())
display(rets.tail())
display(mom.head())
display(ports.head())

        date  Mkt-RF   SMB   HML    RF
0 1926-07-01    2.89 -2.55 -2.39  0.22
1 1926-08-01    2.64 -1.14  3.81  0.25
2 1926-09-01    0.38 -1.36  0.05  0.23
3 1926-10-01   -3.27 -0.14  0.82  0.32
4 1926-11-01    2.54 -0.11 -0.61  0.31

,date,Mkt-RF,SMB,HML,RF,Mom
count,1187,1187.000000,1187.000000,1187.000000,1187.000000,1187.000000
mean,1976-05-31 20:45:53.833192928,0.006893,0.001708,0.003459,0.002700,0.006103
min,1927-01-01 00:00:00,-0.287400,-0.174100,-0.138300,-0.000600,-0.526100
25%,1951-09-16 00:00:00,-0.020050,-0.016300,-0.014400,0.000300,-0.009650
50%,1976-06-01 00:00:00,0.010800,0.000700,0.001400,0.002300,0.007900
75%,2001-02-15 00:00:00,0.036600,0.017400,0.017600,0.004200,0.029400
max,2025-11-01 00:00:00,0.388100,0.359600,0.355200,0.013500,0.180200
std,NaN,0.053205,0.031597,0.035623,0.002496,0.046831

           date       ret
1188 2025-07-01  0.015098
1189 2025-08-01  0.064359
1190 2025-09-01  0.018610
1191 2025-10-01  0.007542
1192 2025-11-01  0.022598

        date   Mom
0 1927-01-01  0.57
1 1927-02-01 -1.50
2 1927-03-01  3.52
3 1927-04-01  4.36
4 1927-05-01  2.78

,date,SMALL LoBM,ME1 BM2,ME1 BM3,ME1 BM4,SMALL HiBM,ME2 BM1,ME2 BM2,ME2 BM3,ME2 BM4,...,ME4 BM1,ME4 BM2,ME4 BM3,ME4 BM4,ME4 BM5,BIG LoBM,ME5 BM2,ME5 BM3,ME5 BM4,BIG HiBM
0,1926-07-01,0.058276,-0.017006,0.005118,-0.021477,0.019583,0.012118,0.024107,0.006056,-0.026082,...,0.015376,0.015460,0.013389,0.002765,0.024678,0.033248,0.060909,0.020285,0.031263,0.005623
1,1926-08-01,-0.020206,-0.080282,0.013968,0.021483,0.085104,0.023620,-0.007525,0.038984,0.002299,...,0.013858,0.038587,0.019738,0.021336,0.053422,0.010169,0.041975,0.019769,0.054924,0.077576
2,1926-09-01,-0.048291,-0.026806,-0.043417,-0.032683,0.008586,-0.026849,-0.005252,0.010789,-0.032877,...,0.016897,-0.005246,-0.017724,0.014806,0.008730,-0.012951,0.036610,0.001384,-0.007497,-0.024284
3,1926-10-01,-0.093633,-0.035519,-0.035024,0.034413,-0.025452,-0.028014,-0.044191,-0.050767,-0.080271,...,-0.039136,-0.026528,-0.021058,-0.032532,-0.053525,-0.027382,-0.030061,-0.022467,-0.046725,-0.058129
4,1926-11-01,0.055888,0.041877,0.024384,-0.044495,0.005110,0.031023,-0.017317,0.030425,0.049538,...,0.034492,0.023823,0.037315,0.051102,0.018213,0.044331,0.025355,0.015280,0.036596,0.025636

In [6]:
import pandas as pd

ff3 = pd.read_parquet("../data/processed/ff3_monthly.parquet")
mom = pd.read_parquet("../data/processed/mom_monthly.parquet")
factors = pd.read_parquet("../data/processed/factors_monthly.parquet")
rets = pd.read_parquet("../data/processed/returns_monthly.parquet")
ports = pd.read_parquet("../data/processed/portfolios_25_5x5_monthly.parquet")
display(ff3.info())
display(mom.info())
display(factors.info())
display(rets.info())
display(ports.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1193 entries, 0 to 1192
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1193 non-null   datetime64[ns]
 1   Mkt-RF  1193 non-null   float64
 2   SMB     1193 non-null   float64
 3   HML     1193 non-null   float64
 4   RF      1193 non-null   float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 46.7 KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1187 non-null   datetime64[ns]
 1   Mom     1187 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 18.7 KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1187 non-null   datetime64[ns]
 1   Mkt-RF  1187 non-null   float64
 2   SMB     1187 non-null   float64
 3   HML     1187 non-null   float64
 4   RF      1187 non-null   float64
 5   Mom     1187 non-null   float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 55.8 KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1193 entries, 0 to 1192
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1193 non-null   datetime64[ns]
 1   ret     1193 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 18.8 KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1193 entries, 0 to 1192
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1193 non-null   datetime64[ns]
 1   SMALL LoBM  1193 non-null   float64
 2   ME1 BM2     1193 non-null   float64
 3   ME1 BM3     1193 non-null   float64
 4   ME1 BM4     1193 non-null   float64
 5   SMALL HiBM  1193 non-null   float64
 6   ME2 BM1     1193 non-null   float64
 7   ME2 BM2     1193 non-null   float64
 8   ME2 BM3     1193 non-null   float64
 9   ME2 BM4     1193 non-null   float64
 10  ME2 BM5     1193 non-null   float64
 11  ME3 BM1     1193 non-null   float64
 12  ME3 BM2     1193 non-null   float64
 13  ME3 BM3     1193 non-null   float64
 14  ME3 BM4     1193 non-null   float64
 15  ME3 BM5     1193 non-null   float64
 16  ME4 BM1     1193 non-null   float64
 17  ME4 BM2     1193 non-null   float64
 18  ME4 BM3     1193 non-null   float64
 19  ME4 BM4     1193 non-null   float64
 20  ME4 BM5     1193 non-null   float64
 21  BIG LoBM    1193 non-null   float64
 22  ME5 BM2     1193 non-null   float64
 23  ME5 BM3     1193 non-null   float64
 24  ME5 BM4     1193 non-null   float64
 25  BIG HiBM    1193 non-null   float64
dtypes: datetime64[ns](1), float64(25)
memory usage: 242.5 KB

None